In [1]:
import numpy as np

In [2]:
x = np.array([1, 7, 9, 8, 5])

In [3]:
x

array([1, 7, 9, 8, 5])

In [4]:
#Indexing: Displays the element given position in array

In [5]:
x[4]

5

In [6]:
#Boolean Indexing

In [7]:
x[x>5]

array([7, 9, 8])

In [8]:
#Fancy Indexing: Displays the elemets in given position in array

In [9]:
x[[2,1]]

array([9, 7])

In [10]:
#Slicing

In [12]:
x = np.random.randn(10,10)

In [13]:
x

array([[ 7.98833345e-01, -1.53526403e+00,  1.37427575e+00,
        -6.84738909e-01, -1.23105265e+00, -1.45627356e+00,
         2.37451455e+00, -3.12010184e-01, -1.64490254e+00,
        -1.90953727e-01],
       [-1.73015884e+00,  3.43976756e-01,  6.85804468e-01,
         1.91210807e-01,  2.67086900e-01, -4.51833078e-01,
        -1.93339090e+00,  5.86682203e-01,  7.23719852e-01,
        -4.04452736e-01],
       [-5.11242329e-01, -4.33746110e-01,  1.44402126e+00,
        -1.25576553e+00, -2.74523465e-03, -7.00670687e-02,
        -2.60261033e-01, -1.07074276e+00,  1.17488480e+00,
         1.87817602e+00],
       [ 1.04662936e+00, -1.19366200e+00,  1.17998261e+00,
         1.33647293e+00, -1.02853464e+00, -7.74146656e-01,
         1.56082463e+00, -1.07326020e+00,  1.21209718e-02,
         2.23567979e-01],
       [-5.81830429e-01,  3.09145672e-01, -1.12205794e+00,
        -2.17127032e-01,  9.69731754e-01,  1.87153425e+00,
         1.71551621e-01,  6.75472016e-01,  5.83226393e-01,
         3.

In [14]:
#Print first row

In [15]:
x[0]

array([ 0.79883334, -1.53526403,  1.37427575, -0.68473891, -1.23105265,
       -1.45627356,  2.37451455, -0.31201018, -1.64490254, -0.19095373])

In [16]:
#Print first row's fifth column

In [17]:
x[0][4]

-1.2310526453725052

In [19]:
x[1:10:2,::]

array([[-1.73015884,  0.34397676,  0.68580447,  0.19121081,  0.2670869 ,
        -0.45183308, -1.9333909 ,  0.5866822 ,  0.72371985, -0.40445274],
       [ 1.04662936, -1.193662  ,  1.17998261,  1.33647293, -1.02853464,
        -0.77414666,  1.56082463, -1.0732602 ,  0.01212097,  0.22356798],
       [ 0.40144088,  1.09321785, -0.22625499, -1.16706523,  0.16419934,
        -0.3728926 ,  0.86502657,  0.11766548,  0.34661172,  0.41666549],
       [ 1.30715917, -0.32842113,  0.24990679, -0.00979751, -0.20186793,
        -0.27010437, -0.9317675 , -1.53041779,  0.56678846, -0.30074687],
       [ 0.7035524 , -2.53324169,  1.60527043, -0.91018928,  0.40453231,
        -0.72430451,  1.75742543, -0.2550976 , -0.06444209, -0.33464807]])

In [20]:
x[::,0:4]

array([[ 0.79883334, -1.53526403,  1.37427575, -0.68473891],
       [-1.73015884,  0.34397676,  0.68580447,  0.19121081],
       [-0.51124233, -0.43374611,  1.44402126, -1.25576553],
       [ 1.04662936, -1.193662  ,  1.17998261,  1.33647293],
       [-0.58183043,  0.30914567, -1.12205794, -0.21712703],
       [ 0.40144088,  1.09321785, -0.22625499, -1.16706523],
       [-1.81576399, -0.03894538, -1.10713773,  0.36794142],
       [ 1.30715917, -0.32842113,  0.24990679, -0.00979751],
       [-0.44962365,  1.71748564, -0.74946324,  1.00218138],
       [ 0.7035524 , -2.53324169,  1.60527043, -0.91018928]])

In [22]:
x = np.ones((5,5))

In [23]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
x[1:-1,1:-1] = 0

In [27]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])