In [2]:
import numpy as np

In [4]:
x = np.zeros((4,4))

In [5]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.empty((7,7))

array([[ 4.68334551e-310,  2.01296774e+152,  0.00000000e+000,
         0.00000000e+000, -1.31337843e+114,  0.00000000e+000,
         0.00000000e+000],
       [ 3.33264260e-158,  0.00000000e+000,  0.00000000e+000,
        -1.04054233e-201,  0.00000000e+000,  0.00000000e+000,
         7.61673128e-296],
       [ 0.00000000e+000,  0.00000000e+000, -1.29816067e-292,
         0.00000000e+000,  0.00000000e+000, -7.09112766e+254,
         0.00000000e+000],
       [ 0.00000000e+000,  3.34728171e-214,  0.00000000e+000,
         0.00000000e+000,  7.49243102e-192,  0.00000000e+000,
         0.00000000e+000],
       [-3.92508356e-135,  0.00000000e+000,  0.00000000e+000,
         7.04830487e-146,  0.00000000e+000,  0.00000000e+000,
        -4.34679890e+136],
       [ 0.00000000e+000,  0.00000000e+000, -1.24019436e+132,
         6.91260394e-310,  6.91260398e-310,  1.49856408e-148,
         0.00000000e+000],
       [ 0.00000000e+000,  8.38316524e-066,  6.91260392e-310,
         6.91260391e-310,  6.139

In [12]:
l = [1, 4, 5, 7]

In [14]:
np.array([l])

array([[1, 4, 5, 7]])

In [16]:
x = np.arange(1, 100, 10)

In [17]:
x.shape

(10,)

In [18]:
x = np.zeros((10,10))

In [19]:
x.shape

(10, 10)

In [22]:
y = x.reshape((2, 2, 5, 5))

In [23]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [25]:
y.dtype

dtype('float64')

In [26]:
y.ndim

4