In [0]:
#Numpy Attributes & Methods

In [0]:
#Numpy Array

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])

In [3]:
#1
#ndarray.data
#Python buffer object pointing to the start of the array’s data
arr = np.array([1,2,3,4,5])
print(arr.data)

In [4]:
#2
#ndarray.size
#Number of elements in the array
arr = np.array([1,2,3,4,5])
print(arr.size)

5


In [5]:
#3
#ndarray.nbytes
#Total bytes consumed by the elements of the array
arr = np.array([1,2,3,4,5])
print(arr.nbytes)

40


In [7]:
#4
#ndarray.strides
#Tuple of bytes to step in each dimension when traversing an array
arr = np.array([1,2,3,4,5])
print(arr.strides)

(8,)


In [8]:
#5
#ndarray.flat
arr = np.array([1,2,3,4,5])
print(arr.flat[0])
print(arr.flat[2])

1
3


In [9]:
#6
#ndarray.ctypes
#An object to simplify the interaction of the array with the ctypes module
arr = np.array([1,2,3,4,5])
print(arr.ctypes)

In [10]:
#7
#ndarray.base
#Base object if memory is from some other object
arr = np.array([1,2,3,4,5])
print(arr.base)

None


In [11]:
#8
#ndarray.compress
#Return selected slices of this array along given axis
arr = np.array([1,2,3,4,5])
print(np.compress([0, 1], arr, axis=0))

[2]


In [12]:
#9
#ndarray.repeat
#Repeat elements of an array
print(np.repeat(3, 4))

[3 3 3 3]


In [13]:
#10
#ndarray.sum
#Return the sum of the array elements over the given axis
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

15


In [14]:
#11
#ndarray.view
#New view of array with the same data
arr = np.array([1,2,3,4,5])
print(arr.view(dtype=np.int16,type=np.matrix))

[[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]]


In [15]:
#12
#ndarray.all
#Returns True if all elements evaluate to True
arr = np.array([1,2,3,4,5])
print(np.all(arr))
print(np.all([0,1,0,0]))

True
False


In [16]:
#13
#ndarray.choose
#Use an index array to construct a new array from a set of choices
choices = [[0, 1, 2, 3], [10, 11, 12, 13],[20, 21, 22, 23], [30, 31, 32, 33]]
print(np.choose([2, 3, 1, 0], choices))

[20 31 12  3]


In [17]:
#14
#ndarray.diagonal
#Return specified diagonals
a=np.array([[1,2],[2,3]])
print(np.diagonal(a))

[1 3]


In [18]:
#15
#ndarray.put
#set a.flat[n] = values[n] for all n in indices
arr = np.array([1,2,3,4,5])
np.put(arr, [0, 2], [-44, -55])
print(arr)

[-44   2 -55   4   5]


In [19]:
#16
#ndarray.take
#Return an array formed from the elements of a at the given indices
a = [5, 7, 2, 3, 4]
indices = [0, 1]
print(np.take(a, indices))

[5 7]


In [20]:
#17
#ndarray.trace
#Return the sum along diagonals of the array
a=np.array([[1,2],[2,3]])
print(np.trace(a))

4


In [21]:
#18
#ndarray.var
#Returns the variance of the array elements, along given axis
a=np.array([[1,2],[2,3]])
print(np.var(a))

0.5


In [22]:
#19
#ndarray.ravel
#Return a flattened array
a=np.array([[1,2],[2,3]])
print(np.ravel(a))

[1 2 2 3]


In [23]:
#20
#ndarray.partition
#Rearranges the elements in the array in such a way that the value of the element in kth position is in the position it would be in a sorted array
a=np.array([1,7,0,5])
a.partition(3)
print(a)

[0 1 5 7]


In [24]:
#21
#ndarray.argmax
#Return indices of the maximum values along the given axis
a=np.array([1,4,0,5])
print(np.argmax(a))

3


In [25]:
#22
#ndarray.argmin
#Return indices of the minimum values along the given axis of a
a=np.array([1,4,0,5])
print(np.argmin(a))

2


In [27]:
#23
#ndarray.ptp
#Peak to peak (maximum - minimum) value along a given axis
a=np.array([1,4,0,5])
print(np.ptp(a))

5


In [28]:
#24
#ndarray.conj
#Complex-conjugate all elements
print(np.conjugate(1+2j))

(1-2j)


In [29]:
#25
#ndarray.argsort
#Returns the indices that would sort this array
a=np.array([1,4,0,5])
print(np.argsort(a))

[2 0 1 3]


In [30]:
#26
#ndarray.argpartition
#Returns the indices that would partition this array
x = np.array([3, 4, 2, 1])
print(x[np.argpartition(x, 3)])

[2 1 3 4]


In [31]:
#27
#ndarray.prod
#Return the product of the array elements over the given axis
a=np.array([1,4,1,5])
print(np.prod(a))

20


In [32]:
#28
#ndarray.std
#Returns the standard deviation of the array elements along given axis
a=np.array([1,4,1,5])
print(np.std(a))

1.7853571071357126


In [33]:
#29
#ndarray.swapaxes
#Return a view of the array with axis1 and axis2 interchanged
a=np.array([[[0,1],[3,5]],[[7,10],[6,7]]])
print(np.swapaxes(a,0,2))

[[[ 0  7]
  [ 3  6]]

 [[ 1 10]
  [ 5  7]]]


In [34]:
#30
#ndarray.transpose
#Returns a view of the array with axes transposed
a = np.array([[3, 9], [8, 4]])
print(np.transpose(a))

[[3 8]
 [9 4]]


In [35]:
#31
#ndarray.shape
#Tuple of array dimensions
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)

(2, 3)


In [36]:
#32
#ndarray.resize
#Change shape and size of array in-place
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
#33
#ndarray.ndm
#Number of array dimensions
import numpy as np 
a = np.arange(24) 
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [37]:
#34
#ndarray.itemsize
#Length of one array element in bytes
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

1


In [39]:
#35
#ndarray.flags
#Information about the memory layout of the array
import numpy as np 
x = np.array([1,2,3,4,5]) 
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [40]:
#36
#ndarray.dtype
#Data-type of the array’s elements
import numpy as np
arr = np.array([1,2,3,4])
print (arr.dtype)

int64


In [41]:
#37
#ndarray.imag
#The imaginary part of the array
import numpy as np
a = np.array([1+3j,5+7j,9+11j])
b = a.imag
print (b)

[ 3.  7. 11.]


In [42]:
#38 
#ndarray.real
#The real part of the array
import numpy as np
arr = np.array([1+3j, 5+7j, 9+11j])
b = arr.real
print (b)

[1. 5. 9.]


In [43]:
#39
#ndarray.clip
#Return an array whose values are limited to [min, max]
inarray = [1,2,3,4,5,6,7,8]
outarray = np.clip(inarray, a_min = 2, a_max = 6)
print(outarray)

[2 2 3 4 5 6 6 6]


In [44]:
#40
#ndarray.copy
#Return a copy of the array
x = np.array([[0,1,2,3], [4,5,6,7]], order ='F')
y=x.copy()
print(y)

[[0 1 2 3]
 [4 5 6 7]]


In [45]:
#41
#ndarray.max
#Return the maximum along a given axis
n = 10
m = 20
print("maximum ",np.maximum(n,m))

maximum  20


In [46]:
#42
#ndarray.min
#Return the minimum along a given axis
print("Minimum",np.minimum(n,m))

Minimum 10


In [47]:
#43
#ndarray.mean
#Returns the average of the array elements along given axis
arr = [20,2,7,1,34]
print(np.mean(arr))

12.8


In [51]:
#44
#ndarray.round
#Return a with each element rounded to the given number of decimals
arr = [.5,1.5,2.5]
round_off = np.round(arr)
print(round_off)

[0. 2. 2.]


In [49]:
#45
#ndarray.sort
#Sort an array in-place
a = np.array([[12,15],[10,1]])
arr1 = np.sort(a,axis = 0)
print(arr1)

[[10  1]
 [12 15]]


In [50]:
#46
#ndarray.squeeze
#Remove single-dimensional entries from the shape of a
arr = np.array([[[2,2,2],[2,2,2]]])
out_arr = np.squeeze(arr)
print(out_arr)

[[2 2 2]
 [2 2 2]]


In [52]:
#47
#ndarray.fill
#Fill the array with a scalar value
a = np.empty([3,3])
for i in range(3):
	for j in range(3):
		a[i][j] = 1
a.fill(1)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
#48
#ndarray.nonzero
#Return the indices of the elements that are non-zero
arr = np.array([[0,8,0], [7,0,0],[-5,0,1]])
out_tpl = np.nonzero(arr)
print(out_tpl)

(array([0, 1, 2, 2]), array([1, 0, 0, 2]))


In [55]:
#49
#ndarray.reshape
#Returns an array containing the same data with a new shape
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr = arr.reshape(4, 3)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [56]:
#50
#ndarray.searchsorted
#Find indices where elements of v should be inserted in a to maintain order
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1
