In [1]:
import numpy as np

In [2]:
a = np.random.randn((10))

In [4]:
b = np.random.randn((10))

In [5]:
a

array([ 0.24324961, -0.51368905, -0.74524793, -1.06289978, -0.37836464,
       -0.7440109 ,  0.90048088, -0.66820643,  0.42227481, -0.76837519])

In [6]:
b

array([-0.96113505,  0.88545349,  0.1689215 ,  0.02247124, -0.98955372,
        1.0989525 ,  1.01846915,  0.0370692 , -1.14191381,  1.23175917])

In [7]:
a+b

array([-0.71788544,  0.37176444, -0.57632643, -1.04042854, -1.36791837,
        0.3549416 ,  1.91895003, -0.63113723, -0.719639  ,  0.46338398])

In [8]:
a-b

array([ 1.20438465, -1.39914253, -0.91416943, -1.08537102,  0.61118908,
       -1.8429634 , -0.11798827, -0.70527563,  1.56418863, -2.00013436])

In [11]:
2*a

array([ 0.48649921, -1.02737809, -1.49049586, -2.12579957, -0.75672929,
       -1.48802179,  1.80096176, -1.33641287,  0.84454963, -1.53675038])

In [12]:
1/a

array([ 4.11100359, -1.94670298, -1.34183532, -0.94082247, -2.64295308,
       -1.34406634,  1.11051775, -1.49654351,  2.36812609, -1.30144754])

In [15]:
a>0

array([ True, False, False, False, False, False,  True, False,  True,
       False])

In [16]:
a[a>0]

array([0.24324961, 0.90048088, 0.42227481])